apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-test
  template:
    metadata:
      labels:
        app: deployment-test
    spec:
      containers:
      - name: deployment-test
        image: us-central1-docker.pkg.dev/ayoba-183a7/gcf-artifacts/deployment-test:v2
        ports: 
        - containerPort: 5000
