apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-test
  template:
    metadata:
      labels:
        app: deployment-test
    spec:
      containers:
      - name: deployment-test
        image: gcr.io/ornate-genre-425416-q8/deployment-test:v3
        ports: 8080
        - containerPort: 5000
